### ISSUE TITLE
/home/amil101/sketchbook/libraries/NanoPlayBoard/src/RotaryEncoder.cpp:33:44: error: cannot declare member function 'static void RotaryEncoder::handleInterrupt()' to have static linkage [-fpermissive]  static void RotaryEncoder::handleInterrupt()

### ISSUE THREAD

**Issue by acien101** [josejuansanchez/sketches_for_arduino_playboard#61]
Con el ejemplo de printChar me sale:
/home/amil101/sketchbook/libraries/NanoPlayBoard/src/RotaryEncoder.cpp:33:44: error: cannot declare member function 'static void RotaryEncoder::handleInterrupt()' to have static linkage [-fpermissive]
 static void RotaryEncoder::handleInterrupt()

Estoy utilizando la primera versión de la placa. 

P:D: YOU ROCK!!

**Comment by josejuansanchez** [comment]
Buenas fiera!

Para utilizar la primera versión de la placa tienes que hacer una pequeña modificación en el archivo `Configuration.h`, porque el pinout ha cambiado entre las dos versiones de la placa.

El archivo `Configuration.h` están en el directorio `src`. Búscalo y verás que tiene este aspecto:

```c++
#ifndef Configuration_h
#define Configuration_h

#define BOARD_MODEL_B

#ifdef BOARD_MODEL_B
  #include "PinsModelB.h"
#else
  #include "PinsModelA.h"
#endif

#define DHT_TYPE   DHT11     // DHT 11
#endif
```

Tienes que eliminar o comentar la definición de la constante `BOARD_MODEL_B`. Por ejemplo:

```c++
#ifndef Configuration_h
#define Configuration_h

//#define BOARD_MODEL_B

#ifdef BOARD_MODEL_B
  #include "PinsModelB.h"
#else
  #include "PinsModelA.h"
#endif

#define DHT_TYPE   DHT11     // DHT 11
#endif
```

Una vez hecho esto la librería usará el pinout definido para la primera versión de la placa.

Pruébalo cuando puedas y me cuentas cómo te ha ido :)

**Comment by josejuansanchez** [comment]
@acien101 ¿Pudiste configurar la librería para trabajar con la primera versión de la placa?
